### ISSUE TITLE
About Virtual KITTI normals

### ISSUE THREAD

**Issue by GonzaloMartinGarcia** [lhoangan/341n143#2]
Hi,

I am currently working with the Virtual KITTI dataset and noticed an issue with accessing the normals data. Unfortunately, the link provided for the dataset appears to be broken, and despite your previous indication that the dataset is no longer available, I was unable to locate the source code necessary to recompute the Virtual KITTI normals myself.

Could you please guide me to the correct source code link, or provide any alternative solutions or datasets that might be available? Your help would be immensely appreciated.

Thank you for your time and assistance.

Best regards,
Martin

**Comment by lhoangan** [comment]
Hi @GonzaloMartinGarcia, thank you for your inquiry. I'm sorry that the computed surface normals for Virtual KITTI are no longer available. In general, the surface normal is the first derivative of depth, so you can simply take the gradient of a depth map. For more sophisticated computation, you can refer to the operation given by [Barron and Malik, Shape, Illumination, and Reflectance from Shading](https://drive.google.com/file/d/1vg9Rb-kBntSTnTCzVgFlskkPXvTB_5aq/view).

Hope it helps.
